import { createHash } from "crypto";
import type { ConsentType } from "@/lib/supabase/types";

export interface ConsentDocument {
  type: ConsentType;
  version: string;
  effectiveDate: string;
  title: string;
  summary: string;
  fullText: string;
  hash: string;
}

/** Hash the consent text so we can prove what the user saw at consent time. */
function hashText(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function defineConsent(
  type: ConsentType,
  version: string,
  effectiveDate: string,
  title: string,
  summary: string,
  fullText: string
): ConsentDocument {
  return { type, version, effectiveDate, title, summary, fullText, hash: hashText(fullText) };
}

// =============================================================================
// CONSENT DOCUMENT REGISTRY
// All consent text is stored in code (not DB) so it's auditable in git history.
// When text changes, bump the version — users on prior versions must re-consent.
// =============================================================================

export const CONSENT_DOCUMENTS: Record<ConsentType, ConsentDocument> = {
  tos: defineConsent(
    "tos",
    "1.0",
    "2026-03-19",
    "Terms of Service",
    "By creating an account, you agree to our Terms of Service governing your use of Meddit.",
    `MEDDIT TERMS OF SERVICE — Version 1.0 — Effective March 19, 2026

1. ACCEPTANCE OF TERMS
By creating an account or using Meddit, you agree to these Terms of Service. If you do not agree, do not use the platform.

2. ELIGIBILITY
You must be at least 18 years old or have legal authority over the medical billing records you upload. Meddit is not intended for use by minors.

3. SERVICE DESCRIPTION
Meddit provides automated medical bill auditing, dispute letter generation, price transparency estimates ("Mestimate"), and access to a legal services directory. Meddit is a document preparation and informational tool. Meddit does NOT provide legal advice, medical advice, or act as your legal representative.

4. DOCUMENT PREPARATION DISCLAIMER
All dispute letters, audit reports, and informational outputs generated by Meddit are tools for your independent use. They do not constitute legal advice, legal opinions, or legal representation. You are solely responsible for reviewing, approving, and sending any documents generated by the platform. Meddit does not submit documents on your behalf.

5. NO GUARANTEE OF OUTCOMES
Audit findings and Mestimate estimates are based on available data and may not reflect your actual costs, coverage, or legal rights. Meddit does not guarantee any financial outcome, dispute resolution, or recovery amount.

6. USER RESPONSIBILITIES
You are responsible for the accuracy of information you provide, including insurance plan details and uploaded documents. You must review all generated documents before use.

7. LIMITATION OF LIABILITY
To the maximum extent permitted by law, Meddit shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform.

8. MODIFICATIONS
We may update these Terms. Material changes will require re-acceptance before continued use of gated features.`
  ),

  privacy_policy: defineConsent(
    "privacy_policy",
    "1.0",
    "2026-03-19",
    "Privacy Policy",
    "Our privacy policy explains how we collect, use, and protect your personal information.",
    `MEDDIT PRIVACY POLICY — Version 1.0 — Effective March 19, 2026

1. INFORMATION WE COLLECT
- Account information: name, email address, state of residence
- Insurance profile: insurer name, plan type
- Usage data: pages visited, features used, timestamps

2. HOW WE USE YOUR INFORMATION
- To provide and improve the Meddit platform
- To communicate with you about your account and our services
- To comply with legal obligations

3. INFORMATION WE DO NOT COLLECT IN THIS POLICY
Health data (medical bills, EOBs, insurance documents) is covered under a SEPARATE health data consent that you will be asked to provide before uploading any health-related documents. This privacy policy does not authorize collection of health data.

4. DATA SHARING
We do not sell your personal information to third parties. We do not share your data with advertising partners. We may share data with service providers who help operate our platform (hosting, email delivery) under strict data processing agreements.

5. YOUR RIGHTS
- Access: You may request a copy of your personal data at any time.
- Deletion: You may request deletion of your account and personal data.
- Correction: You may update your profile information at any time.

6. STATE-SPECIFIC RIGHTS
If you are a California resident, you have additional rights under the CCPA/CPRA. If you are a Washington state resident, you have additional rights under the My Health My Data Act. Contact support@meddit.com to exercise these rights.

7. DATA SECURITY
We use industry-standard encryption and access controls to protect your data. However, no system is 100% secure.

8. CHANGES TO THIS POLICY
Material changes will require re-acceptance. We will notify you of changes via email.

9. CONTACT
support@meddit.com`
  ),

  health_data_upload: defineConsent(
    "health_data_upload",
    "1.0",
    "2026-03-19",
    "Health Data Consent",
    "Separate consent required before uploading medical bills, EOBs, or other health-related documents.",
    `MEDDIT HEALTH DATA CONSENT — Version 1.0 — Effective March 19, 2026

IMPORTANT: This is a separate consent from the Terms of Service and Privacy Policy. Under the Washington My Health My Data Act and the California Consumer Privacy Act (CCPA/CPRA), your medical billing data is classified as sensitive health data requiring specific, informed consent before collection.

1. WHAT DATA THIS COVERS
This consent covers medical bills, Explanation of Benefits (EOBs), itemized hospital bills, insurance statements, and any other health-related financial documents you upload to Meddit.

2. HOW WE USE YOUR HEALTH DATA
Your uploaded health documents will be used to:
- Parse and extract billing information (provider, procedure codes, charges, adjustments)
- Compare your charges against public pricing benchmarks (CMS Medicare rates, published hospital prices)
- Generate audit findings identifying potential overcharges or billing errors
- Generate dispute letter templates populated with facts from your documents
- Display price comparison estimates ("Mestimate") based on your procedures

3. HOW WE PROTECT YOUR HEALTH DATA
- Documents are encrypted at rest and in transit
- Access is restricted to your authenticated account
- We do not share your individual health documents with third parties
- We do not use your health data for advertising

4. WHAT THIS CONSENT DOES NOT AUTHORIZE
This consent does NOT authorize:
- Sale or sharing of your identifiable health data with third parties
- Use of your data for purposes other than those listed in Section 2
- Sharing your documents with other users, providers, or insurers

If we wish to use your data for additional purposes (such as anonymized aggregate research), we will ask for separate consent at that time.

5. YOUR RIGHT TO REVOKE
You may revoke this consent at any time. Revoking consent will:
- Immediately prevent further processing of your uploaded documents
- Delete all uploaded documents from our storage within 30 days
- Preserve your account and non-health personal data
To revoke, visit your account settings or contact support@meddit.com.

6. YOUR RIGHT TO DELETE
Under the WA My Health My Data Act and CCPA/CPRA, you have the right to request deletion of all health data we hold about you. We will comply within 30 days.

7. HIPAA NOTICE
Meddit is not a healthcare provider, health plan, or healthcare clearinghouse. We are not a "Covered Entity" under HIPAA. When you upload your own medical documents, you are exercising your right to access and use your own health information. We do not maintain Business Associate Agreements with healthcare providers on your behalf.

8. MEDDIT IS NOT A HEALTHCARE PROVIDER
Meddit does not provide medical advice, diagnoses, or treatment recommendations. All health-related outputs are informational only.`
  ),

  marketplace_data_sharing: defineConsent(
    "marketplace_data_sharing",
    "1.0",
    "2026-03-19",
    "Marketplace Data Sharing",
    "Consent to share limited profile data with marketplace service providers.",
    `MEDDIT MARKETPLACE DATA SHARING CONSENT — Version 1.0 — Effective March 19, 2026

PLACEHOLDER: This consent will be activated when marketplace features launch. It will authorize limited sharing of your profile data (insurer, plan type, state, service needs) with marketplace participants (attorneys, health service providers, insurance companies) to facilitate service matching.

This consent is separate from health data consent and will not authorize sharing of your uploaded medical documents.`
  ),

  aggregate_data_monetization: defineConsent(
    "aggregate_data_monetization",
    "1.0",
    "2026-03-19",
    "Aggregate Data Research",
    "Consent to include your anonymized, de-identified data in aggregate research datasets.",
    `MEDDIT AGGREGATE DATA RESEARCH CONSENT — Version 1.0 — Effective March 19, 2026

PLACEHOLDER: This consent will be activated when our data program launches. It will authorize Meddit to include your ANONYMIZED and DE-IDENTIFIED billing data in aggregate research datasets. Your individual identity, documents, and personal information will NEVER be included. Only statistical aggregates (e.g., "average charge for procedure X in region Y") derived from many users' data.

This is separate from all other consents. Declining this consent will not affect your access to any Meddit features.`
  ),
};

/** Get the current consent document for a given type. */
export function getConsentDocument(type: ConsentType): ConsentDocument {
  return CONSENT_DOCUMENTS[type];
}

/** Get all consent types required at a specific trigger point. */
export function getRequiredConsents(
  trigger: "signup" | "upload" | "marketplace" | "data_monetization"
): ConsentType[] {
  switch (trigger) {
    case "signup":
      return ["tos", "privacy_policy"];
    case "upload":
      return ["health_data_upload"];
    case "marketplace":
      return ["marketplace_data_sharing"];
    case "data_monetization":
      return ["aggregate_data_monetization"];
  }
}
