import { createHash } from "crypto";
import type { ConsentType } from "@/lib/supabase/types";

export interface ConsentDocument {
  type: ConsentType;
  version: string;
  effectiveDate: string;
  title: string;
  summary: string;
  fullText: string;
  hash: string;
}

/** Hash the consent text so we can prove what the user saw at consent time. */
function hashText(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function defineConsent(
  type: ConsentType,
  version: string,
  effectiveDate: string,
  title: string,
  summary: string,
  fullText: string
): ConsentDocument {
  return { type, version, effectiveDate, title, summary, fullText, hash: hashText(fullText) };
}

// =============================================================================
// CONSENT DOCUMENT REGISTRY
// All consent text is stored in code (not DB) so it's auditable in git history.
// When text changes, bump the version — users on prior versions must re-consent.
// =============================================================================

export const CONSENT_DOCUMENTS: Record<ConsentType, ConsentDocument> = {
  // ===========================================================================
  // #5 — TERMS OF SERVICE (v1.1)
  // Covers: service scope, CROA-safe document prep disclaimer, subscriptions,
  //         IP, liability, indemnification, arbitration, governing law.
  // ===========================================================================
  tos: defineConsent(
    "tos",
    "1.1",
    "2026-03-25",
    "Terms of Service",
    "By creating an account, you agree to our Terms of Service governing your use of Candid.",
    `CANDID TERMS OF SERVICE
Version 1.1 — Effective March 25, 2026
Operated by Airgetlam Labs LLC

1. ACCEPTANCE OF TERMS
By creating an account or using any Candid service, you ("you" or "User") agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not create an account or use the platform. These Terms constitute a legally binding agreement between you and Airgetlam Labs LLC ("Candid," "we," "us," or "our").

2. ELIGIBILITY
You must be at least 18 years of age and legally capable of entering into binding contracts. By using Candid, you represent that you have legal authority over any medical billing records or insurance documents you upload. Candid is not intended for use by minors.

3. SERVICE DESCRIPTION
Candid is a consumer financial technology platform that provides the following services:
(a) Candid Claim (Free Tier) — Automated medical bill auditing that identifies potential overcharges, billing errors, unbundling violations, upcoding, and duplicate charges by comparing your bills against public pricing benchmarks.
(b) Candid Plan — Insurance benefits analysis that identifies covered benefits, in-network advantages, and cost-sharing opportunities you may not be utilizing.
(c) Candid Claim (Paid Tier) — Dispute letter generation, documentation aggregation, and guided dispute workflows to help you contest identified billing errors.
(d) Candid Case — A directory of attorneys who specialize in healthcare billing disputes, medical debt, and insurance coverage issues.
(e) Candid Care — Price transparency estimates comparing procedure costs across providers in your area, powered by aggregated public and user-contributed data.

4. DOCUMENT PREPARATION — NOT LEGAL ADVICE
IMPORTANT: Candid is a document preparation and informational tool. Candid does NOT provide legal advice, legal opinions, legal representation, medical advice, or act as your attorney or advocate.
All dispute letters, audit reports, and informational outputs generated by Candid are tools for your independent use. You are solely responsible for:
- Reviewing all generated documents for accuracy before use
- Deciding whether and when to send any document
- Physically sending any correspondence yourself
Candid never submits, files, or sends documents on your behalf. You maintain full control over all communications with providers, insurers, and other parties. This structure is maintained to ensure compliance with the Credit Repair Organizations Act (15 U.S.C. §1679) and applicable state consumer protection laws.

5. NO GUARANTEE OF OUTCOMES
Audit findings, benefit analyses, and cost estimates are based on publicly available data and the information you provide. They may not reflect your actual costs, coverage terms, or legal rights. Candid does not guarantee any financial outcome, dispute resolution, billing adjustment, or recovery amount. Past results for other users do not predict your results.

6. USER RESPONSIBILITIES
You agree to:
(a) Provide accurate and complete information, including insurance plan details and uploaded documents
(b) Review all generated documents before use
(c) Not use Candid for any unlawful purpose or to submit fraudulent claims
(d) Not attempt to reverse-engineer, scrape, or systematically extract data from the platform
(e) Maintain the security of your account credentials
(f) Promptly notify us of any unauthorized access to your account

7. ACCOUNT AND SUBSCRIPTION TERMS
(a) Free Tier — Candid Claim (free audit) and Candid Plan are available at no charge, subject to usage limits we may establish.
(b) Paid Subscription — Access to premium features (paid Candid Claim, Candid Case, Candid Care) requires an active subscription. Subscription fees, billing cycles, and included features are displayed at the time of purchase.
(c) Billing — Subscriptions are billed in advance on a recurring basis (monthly or annually, as selected). Payment is processed through Stripe, Inc. You authorize us to charge your selected payment method.
(d) Cancellation — You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of your current billing period. No partial refunds are provided for unused portions of a billing period.
(e) Price Changes — We may change subscription prices with 30 days' notice. Price changes take effect at the start of your next billing period after the notice.

8. INTELLECTUAL PROPERTY
All content, software, algorithms, designs, and documentation comprising the Candid platform are owned by Airgetlam Labs LLC or its licensors. You retain ownership of all documents you upload. You grant us a limited license to process your uploaded documents solely for the purpose of providing the services described in Section 3. This license terminates when you delete your documents or close your account.

9. LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AIRGETLAM LABS LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF OR INABILITY TO USE THE PLATFORM. OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING FROM THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED DOLLARS ($100), WHICHEVER IS GREATER.

10. INDEMNIFICATION
You agree to indemnify and hold harmless Airgetlam Labs LLC, its officers, employees, and agents from any claims, damages, losses, or expenses (including reasonable attorneys' fees) arising from: (a) your use of the platform, (b) your violation of these Terms, (c) your use of any documents generated by Candid, or (d) your interactions with providers, insurers, attorneys, or other third parties facilitated through Candid.

11. DISPUTE RESOLUTION
(a) Informal Resolution — Before filing any formal proceeding, you agree to contact us at support@candid.com and attempt to resolve the dispute informally for at least 30 days.
(b) Binding Arbitration — Any dispute not resolved informally shall be resolved by binding arbitration administered by the American Arbitration Association ("AAA") under its Consumer Arbitration Rules. Arbitration shall be conducted in English, and the arbitrator's decision shall be final and binding.
(c) Class Action Waiver — You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.
(d) Small Claims Exception — Either party may bring an individual action in small claims court if the claim falls within that court's jurisdiction.
(e) Opt-Out — You may opt out of this arbitration agreement by sending written notice to support@candid.com within 30 days of creating your account.

12. GOVERNING LAW
These Terms are governed by the laws of the State of Delaware, without regard to conflict-of-law principles. For any disputes not subject to arbitration, you consent to the exclusive jurisdiction of the state and federal courts located in Delaware.

13. TERMINATION
We may suspend or terminate your account if you violate these Terms or engage in activity that harms Candid, other users, or third parties. You may close your account at any time. Upon termination, your right to use the platform ceases immediately. Sections 4, 5, 9, 10, 11, and 12 survive termination.

14. SEVERABILITY
If any provision of these Terms is found unenforceable, the remaining provisions remain in full effect.

15. ENTIRE AGREEMENT
These Terms, together with our Privacy Policy, Health Data Consent, and any other consent documents you accept, constitute the entire agreement between you and Airgetlam Labs LLC regarding the Candid platform.

16. MODIFICATIONS
We may update these Terms at any time. Material changes will be communicated via email and will require re-acceptance before continued use of gated features. Your continued use of Candid after re-acceptance constitutes agreement to the updated Terms.

17. CONTACT
Airgetlam Labs LLC
Email: support@candid.com`
  ),

  // ===========================================================================
  // #6 — PRIVACY POLICY (v1.1)
  // Covers: data categories, purposes, processors, retention, no sale,
  //         CCPA/CPRA rights, WA MHMD Act rights, cookies, security, children.
  // ===========================================================================
  privacy_policy: defineConsent(
    "privacy_policy",
    "1.1",
    "2026-03-25",
    "Privacy Policy",
    "Our privacy policy explains how we collect, use, and protect your personal information.",
    `CANDID PRIVACY POLICY
Version 1.1 — Effective March 25, 2026
Operated by Airgetlam Labs LLC

1. SCOPE
This Privacy Policy describes how Airgetlam Labs LLC ("Candid," "we," "us") collects, uses, and protects your personal information when you use the Candid platform. This policy covers your account and profile data only. Collection of health-related data (medical bills, EOBs, insurance documents) is governed by a separate Health Data Consent that you must accept before uploading any health documents.

2. INFORMATION WE COLLECT

(a) Account Information — When you create an account, we collect:
- Full legal name
- Email address
- State of residence
- Authentication credentials (password hash or third-party OAuth token)

(b) Insurance Profile — When you set up your profile, you may provide:
- Insurance company name
- Plan name and type (employer, marketplace, off-exchange, Medicare, Medicaid)
- Matched plan identifier (if using CMS marketplace plan data)

(c) Usage Data — We automatically collect:
- Pages visited and features used
- Timestamps of activity
- Device type and browser type (not fingerprinted or shared)
- IP address (used for security and fraud prevention only; not shared with third parties)

(d) Support Communications — When you contact support, we retain your messages and our responses.

(e) Payment Information — Subscription payment details are collected and processed directly by Stripe, Inc. We do not store your credit card number, bank account number, or other payment instrument details on our servers. We receive from Stripe only: subscription status, billing period, and a truncated card identifier for display purposes.

3. INFORMATION WE DO NOT COLLECT UNDER THIS POLICY
Health data (medical bills, EOBs, insurance documents, audit results, billing codes) is NOT covered by this Privacy Policy. Collection and use of health data requires separate, informed consent under our Health Data Consent document. This separation is required by the Washington My Health My Data Act and recommended under CCPA/CPRA for sensitive data categories.

4. HOW WE USE YOUR INFORMATION
We use your personal information to:
- Provide, maintain, and improve the Candid platform
- Authenticate your identity and secure your account
- Match you with relevant insurance plan data from public sources (CMS Marketplace API)
- Communicate with you about your account, service updates, and support requests
- Process subscription payments
- Comply with legal obligations
- Detect and prevent fraud or unauthorized access

We do NOT use your personal information for:
- Targeted advertising
- Sale to data brokers
- Profiling for credit, insurance, or employment decisions

5. THIRD-PARTY SERVICE PROVIDERS
We share limited personal data with the following service providers, each operating under data processing agreements:

| Provider | Purpose | Data Shared |
|----------|---------|-------------|
| Supabase (Supabase Inc.) | Database hosting | Account info, profile, usage records |
| Firebase / Google Cloud Platform | Authentication, file storage | Email, auth tokens, uploaded files |
| Stripe, Inc. | Payment processing | Email, subscription events |
| Resend (Resend Inc.) | Transactional email | Email address, name |
| Vercel Inc. | Application hosting | IP address (server logs, auto-deleted) |

We do not share your data with advertising networks, social media platforms, or data brokers.

6. DATA RETENTION
- Account data is retained for the lifetime of your account.
- Upon account deletion, personal data is removed within 30 days.
- Server access logs (containing IP addresses) are retained for no more than 90 days.
- Payment records may be retained as required by tax and financial regulations.
- Support communications are retained for 2 years after resolution, then deleted.

7. WE DO NOT SELL YOUR DATA
Candid does not sell, rent, or trade your personal information to third parties. This applies to all categories of personal information we collect. For the purposes of the California Consumer Privacy Act (CCPA/CPRA), we confirm: we have not sold personal information in the preceding 12 months and do not intend to do so.

8. COOKIES AND TRACKING
Candid uses only essential, first-party cookies required for authentication and session management. We do not use:
- Third-party tracking cookies
- Advertising pixels or beacons
- Cross-site tracking technologies
- Analytics platforms that share data with third parties

9. YOUR RIGHTS — ALL USERS
Regardless of where you reside, you have the right to:
- Access: Request a copy of your personal data
- Correction: Update or correct inaccurate personal data
- Deletion: Request deletion of your account and personal data
- Portability: Request your data in a structured, machine-readable format
To exercise these rights, email support@candid.com or use the account settings page.

10. YOUR RIGHTS — CALIFORNIA RESIDENTS (CCPA/CPRA)
If you are a California resident, you have additional rights under the California Consumer Privacy Act, as amended by the California Privacy Rights Act:
- Right to Know: You may request the specific categories and pieces of personal information we have collected about you, the sources, the business purposes, and the categories of third parties with whom we share it.
- Right to Delete: You may request deletion of personal information we hold about you, subject to legal exceptions.
- Right to Correct: You may request correction of inaccurate personal information.
- Right to Opt Out of Sale/Sharing: We do not sell or share your personal information for cross-context behavioral advertising. No opt-out is necessary, but you may submit one at support@candid.com for your records.
- Right to Limit Use of Sensitive Personal Information: Your health data is governed by a separate consent. We do not use sensitive personal information for purposes beyond what is needed to provide our services.
- Non-Discrimination: We will not discriminate against you for exercising your CCPA/CPRA rights.
To submit a verifiable consumer request, email support@candid.com. We will respond within 45 days.

11. YOUR RIGHTS — WASHINGTON STATE RESIDENTS (MY HEALTH MY DATA ACT)
If you are a Washington state resident, you have additional rights under the Washington My Health My Data Act (RCW 19.373):
- Your consumer health data (including medical billing records) requires separate, specific consent before collection — provided through our Health Data Consent document.
- You may revoke consent for health data collection at any time.
- You may request deletion of all consumer health data within 30 days.
- We will never sell your consumer health data without separate, explicit consent.
- We will never geofence healthcare facilities to collect or infer health data.
- You have a private right of action under the Washington Consumer Protection Act (RCW 19.86) if we violate these provisions.
Health data rights are exercised through the Health Data Consent document and at support@candid.com.

12. CHILDREN'S PRIVACY
Candid is not intended for use by individuals under 18 years of age. We do not knowingly collect personal information from children. If we learn that we have collected data from a child under 18, we will delete it promptly.

13. INTERNATIONAL USERS
Candid is operated from the United States. If you access Candid from outside the United States, your data will be transferred to and processed in the United States. By using Candid, you consent to this transfer.

14. DATA SECURITY
We implement industry-standard security measures including:
- Encryption in transit (TLS 1.2+)
- Encryption at rest (AES-256 for stored data)
- Role-based access controls
- Authentication via Firebase with secure token management
- Regular access reviews
No system is 100% secure. We cannot guarantee absolute security but will notify affected users promptly in the event of a data breach, consistent with applicable state breach notification laws.

15. CHANGES TO THIS POLICY
We may update this Privacy Policy. Material changes will be communicated via email and will require re-acceptance. The "Effective" date at the top indicates the latest version.

16. CONTACT
Airgetlam Labs LLC
Email: support@candid.com`
  ),

  // ===========================================================================
  // #7 — HEALTH DATA CONSENT (v1.1)
  // WA My Health My Data Act compliant: separate consent, specific categories,
  // specific purposes, named processors, retention period, revocation, deletion.
  // Also addresses CCPA/CPRA sensitive data and HIPAA non-applicability.
  // ===========================================================================
  health_data_upload: defineConsent(
    "health_data_upload",
    "1.1",
    "2026-03-25",
    "Health Data Consent",
    "Separate consent required before uploading medical bills, EOBs, or other health-related documents.",
    `CANDID HEALTH DATA CONSENT
Version 1.1 — Effective March 25, 2026
Operated by Airgetlam Labs LLC

IMPORTANT: This is a SEPARATE consent from the Terms of Service and Privacy Policy. Under the Washington My Health My Data Act (RCW 19.373) and the California Consumer Privacy Act (CCPA/CPRA), your medical billing data is classified as sensitive consumer health data requiring specific, informed consent before collection. You must accept this consent before uploading any health-related documents to Candid.

1. CATEGORIES OF HEALTH DATA COLLECTED
When you upload documents to Candid, we may collect and process the following categories of consumer health data:
- Medical bills and itemized hospital bills (provider names, dates of service, charge amounts)
- Explanation of Benefits (EOB) documents (insurer determinations, allowed amounts, patient responsibility)
- Insurance statements and Summary of Benefits and Coverage (SBC) documents
- Procedure codes (CPT, HCPCS) and diagnosis codes (ICD-10) extracted from your documents
- Provider names, facility names, and National Provider Identifiers (NPIs) from your documents
- Charge amounts, payment amounts, adjustment amounts, and balance-due amounts
We do NOT collect or store: Social Security numbers, medical record numbers, clinical notes, lab results, prescription information, or diagnostic images. If such information appears in uploaded documents, we do not extract or retain it.

2. SPECIFIC PURPOSES FOR WHICH YOUR HEALTH DATA IS USED
Your uploaded health documents will be used exclusively for:
(a) Bill Parsing — Extracting structured billing data (provider, codes, charges, adjustments) from your uploaded documents using optical character recognition (OCR) and document analysis.
(b) Audit Analysis — Comparing your charges against public pricing benchmarks (CMS Medicare Physician Fee Schedule, published hospital price transparency files) to identify potential overcharges, billing errors, unbundling violations, upcoding, and duplicate charges.
(c) Benefit Matching — Comparing procedures on your bills against your insurance plan's covered benefits to identify coverage gaps or missed in-network savings.
(d) Dispute Letter Generation — Populating dispute letter templates with facts extracted from your documents, including provider names, dates, codes, and charge amounts. You review and send all letters yourself.
(e) Cost Estimation — Displaying price comparison estimates for your specific procedures across providers in your area.
Your health data will NOT be used for any purpose not listed above without obtaining separate, additional consent.

3. THIRD-PARTY PROCESSORS WHO ACCESS YOUR HEALTH DATA
The following service providers may process your health data under strict data processing agreements:

| Processor | Purpose | Data Accessed |
|-----------|---------|---------------|
| Google Cloud Platform (Document AI) | OCR and document parsing | Uploaded document images (processed, not stored by Google beyond processing) |
| Supabase (Supabase Inc.) | Encrypted database storage | Extracted billing data, audit results |
| Firebase / Google Cloud Storage | Encrypted file storage | Original uploaded document files |

No other third party receives, accesses, or processes your identifiable health data. We do not share your health documents with advertisers, data brokers, insurers, providers, employers, or any other party.

4. DATA RETENTION AND STORAGE
- Your uploaded documents and extracted data are retained for the lifetime of your account or until you delete them, whichever comes first.
- Upon consent revocation, all uploaded documents and extracted health data are deleted within 30 days.
- Upon account deletion, all health data is deleted within 30 days.
- Encrypted backups that may contain health data are purged within 90 days of deletion.
- Health data is encrypted at rest (AES-256) and in transit (TLS 1.2+).

5. WHAT THIS CONSENT DOES NOT AUTHORIZE
This consent does NOT authorize:
- Sale of your identifiable health data to any third party — ever
- Sharing your documents or extracted data with insurers, providers, employers, or other users
- Use of your health data for advertising, marketing, or profiling
- Use of your health data for purposes other than those listed in Section 2
- Geofencing of healthcare facilities to collect or infer health data about you
If we wish to use your data for additional purposes (such as anonymized aggregate research), we will request separate, additional consent at that time.

6. YOUR RIGHT TO REVOKE CONSENT
You may revoke this health data consent at any time. Revoking consent will:
- Immediately prevent further processing of your uploaded documents
- Queue all uploaded documents and extracted health data for deletion within 30 days
- Preserve your account, subscription, and non-health personal data
- Not affect the legality of processing performed before revocation
To revoke, visit your account settings and select "Revoke Health Data Consent," or email support@candid.com.

7. YOUR RIGHT TO DELETE
Under the Washington My Health My Data Act and CCPA/CPRA, you have the right to request deletion of all consumer health data we hold about you. Upon receiving a verified deletion request, we will:
- Delete all uploaded documents from file storage within 30 days
- Delete all extracted billing data, audit results, and dispute letter drafts within 30 days
- Confirm deletion to you in writing
To request deletion, email support@candid.com with the subject "Health Data Deletion Request."

8. YOUR RIGHT TO ACCESS
You may request a copy of all health data we hold about you. We will provide it in a structured, machine-readable format (JSON or CSV) within 30 days.

9. HIPAA NOTICE
Candid is not a healthcare provider, health plan, healthcare clearinghouse, or Business Associate as defined under the Health Insurance Portability and Accountability Act (HIPAA). When you upload your own medical documents to Candid, you are exercising your right to access, use, and share your own health information as a consumer.
While HIPAA does not directly regulate Candid, we voluntarily adopt security practices consistent with the HIPAA Security Rule as a best-practice standard for protecting your health data. See our HIPAA Storage Practices documentation for details.

10. CANDID IS NOT A HEALTHCARE PROVIDER
Candid does not provide medical advice, diagnoses, treatment recommendations, or clinical opinions. All health-related outputs (audit findings, benefit analyses, cost estimates) are informational tools for your independent use. Always consult qualified healthcare and legal professionals for advice specific to your situation.

11. WASHINGTON STATE RESIDENTS — ADDITIONAL RIGHTS
Under the My Health My Data Act, Washington residents have the right to:
- Receive this consent in a clear, standalone format (separate from Terms of Service)
- Know the specific categories of health data collected and each purpose for collection
- Know the specific categories of third parties and affiliates with whom health data is shared
- Revoke consent and have health data deleted within 30 days
- Bring a private cause of action under the Washington Consumer Protection Act (RCW 19.86) for violations
This consent document is designed to satisfy all requirements of RCW 19.373.

12. CONTACT
For questions about this Health Data Consent or to exercise your rights:
Airgetlam Labs LLC
Email: support@candid.com`
  ),

  // ===========================================================================
  // MARKETPLACE DATA SHARING CONSENT (v1.1)
  // Replaces placeholder with real consent for when marketplace features launch.
  // ===========================================================================
  marketplace_data_sharing: defineConsent(
    "marketplace_data_sharing",
    "1.1",
    "2026-03-25",
    "Marketplace Data Sharing",
    "Consent to share limited profile data with marketplace service providers when using Candid Case or Candid Care.",
    `CANDID MARKETPLACE DATA SHARING CONSENT
Version 1.1 — Effective March 25, 2026
Operated by Airgetlam Labs LLC

This consent is required before using Candid's marketplace features (Candid Case attorney directory and Candid Care provider listings). This is a SEPARATE consent from the Terms of Service, Privacy Policy, and Health Data Consent.

1. WHAT DATA IS SHARED
When you use marketplace features, the following profile-level data may be shared with listed service providers:
- Your state of residence
- Your insurance company and plan type (e.g., "BlueCross PPO")
- The general category of service you are seeking (e.g., "billing dispute attorney," "physical therapy")
- Your preferred contact method (email only — we never share your phone number)

2. WHAT IS NEVER SHARED
The following data is NEVER shared with marketplace participants:
- Your uploaded medical documents, bills, or EOBs
- Audit results, dispute letters, or extracted billing data
- Your full name (unless you choose to provide it directly to a provider)
- Your payment information
- Your usage history or activity on Candid

3. WHO RECEIVES YOUR DATA
Marketplace participants include:
(a) Attorneys listed in the Candid Case directory who specialize in healthcare billing disputes
(b) Health service providers listed in Candid Care (e.g., physical therapists, nutritionists, HSA/FSA-eligible providers)
(c) Insurance companies or brokers offering alternative or supplemental plan options
All marketplace participants operate under flat-fee listing agreements with Candid. We do not charge per-referral fees or receive commissions based on your interactions with them.

4. PURPOSE
Data sharing is used exclusively for service matching — connecting you with relevant professionals based on your location, insurance, and service needs. We do not use marketplace data for advertising, profiling, or any purpose other than facilitating the connection you requested.

5. YOUR RIGHT TO REVOKE
You may revoke this consent at any time. Revoking consent will:
- Immediately prevent further data sharing with marketplace participants
- Disable your access to Candid Case and Candid Care marketplace features
- Not affect data already shared with providers you previously contacted
- Preserve your account and all other features (audit, benefits analysis, dispute letters)
To revoke, visit your account settings or email support@candid.com.

6. CONTACT
Airgetlam Labs LLC
Email: support@candid.com`
  ),

  // ===========================================================================
  // #9 — AGGREGATE DATA RESEARCH CONSENT (v1.1)
  // Replaces placeholder. Covers de-identification methodology, what's included
  // and excluded, right to opt out, no impact on features.
  // ===========================================================================
  aggregate_data_monetization: defineConsent(
    "aggregate_data_monetization",
    "1.1",
    "2026-03-25",
    "Aggregate Data Research",
    "Consent to include your anonymized, de-identified data in aggregate research datasets.",
    `CANDID AGGREGATE DATA RESEARCH CONSENT
Version 1.1 — Effective March 25, 2026
Operated by Airgetlam Labs LLC

This consent is SEPARATE from all other Candid consents (Terms of Service, Privacy Policy, Health Data Consent, and Marketplace Data Sharing). Declining this consent will NOT affect your access to any Candid feature.

1. WHAT THIS CONSENT AUTHORIZES
By accepting this consent, you authorize Candid to include data derived from your uploaded documents in anonymized, de-identified, aggregate research datasets. These datasets power the Candid Care price transparency tool and may be made available to researchers, journalists, policymakers, and consumer advocacy organizations working to improve healthcare pricing transparency.

2. DE-IDENTIFICATION METHODOLOGY
Before any data is included in aggregate datasets, it is de-identified using the HIPAA Safe Harbor method (45 CFR 164.514(b)(2)). This means ALL of the following identifiers are removed:
- Names and initials
- Dates more specific than year (date of birth, admission dates, discharge dates)
- Addresses and zip codes (reduced to first 3 digits only, or removed if population < 20,000)
- Phone numbers, email addresses, and fax numbers
- Social Security numbers and medical record numbers
- Health plan beneficiary numbers
- Account numbers and certificate/license numbers
- Device identifiers, vehicle identifiers, and serial numbers
- Web URLs, IP addresses, and biometric identifiers
- Full-face photographs
- Any other unique identifying number or code

3. WHAT IS INCLUDED IN AGGREGATE DATASETS
Only statistical aggregates derived from many users' de-identified data, such as:
- Average, median, and range of charges for a given procedure code in a geographic region
- Frequency of specific billing patterns (e.g., unbundling rates by provider type)
- Insurance plan coverage statistics (e.g., "X% of PPO plans cover this benefit")
- Price variation indices across facilities and regions

4. WHAT IS NEVER INCLUDED
Your individual identity, documents, and personal information are NEVER included. Specifically:
- Your name, email, or any account information
- Your individual bills, EOBs, or uploaded documents
- Any data that could reasonably be used to identify you
- Your audit results, dispute letters, or case history

5. HOW AGGREGATE DATA IS USED
Aggregate datasets may be used for:
(a) Powering the Candid Care price transparency tool for all users
(b) Published research reports on healthcare pricing trends
(c) Licensed access by researchers, journalists, and advocacy organizations
(d) Public policy analysis and regulatory submissions
Aggregate data is NEVER used for: targeted advertising, individual credit or insurance decisions, employer screening, or law enforcement purposes.

6. YOUR RIGHT TO OPT OUT
You may revoke this consent at any time. Revoking consent will:
- Exclude your data from future aggregate dataset updates
- Not remove your previously contributed data from datasets already published or distributed (because it is de-identified and cannot be traced back to you)
- Not affect your access to any Candid feature
To revoke, visit your account settings or email support@candid.com.

7. COMPENSATION
You will not receive financial compensation for data included in aggregate datasets. The benefit to you is improved price transparency data within the Candid Care tool, which all users share.

8. CONTACT
Airgetlam Labs LLC
Email: support@candid.com`
  ),
};

/** Get the current consent document for a given type. */
export function getConsentDocument(type: ConsentType): ConsentDocument {
  return CONSENT_DOCUMENTS[type];
}

/** Get all consent types required at a specific trigger point. */
export function getRequiredConsents(
  trigger: "signup" | "upload" | "marketplace" | "data_monetization"
): ConsentType[] {
  switch (trigger) {
    case "signup":
      return ["tos", "privacy_policy"];
    case "upload":
      return ["health_data_upload"];
    case "marketplace":
      return ["marketplace_data_sharing"];
    case "data_monetization":
      return ["aggregate_data_monetization"];
  }
}
