/**
 * Generate progress-tracker.md — human-readable pivot table.
 *
 * Two main views:
 *   1. Per-state per-doc summary table (fields_verifiable / spurious_null / drift / fmt_fail / cost)
 *   2. Per-state per-field disagreements-with-Opus drill-down (for review)
 *   3. Ground truth coverage summary (how many fields have unambiguous truth per doc)
 */

import type { CalibrationState, GroundTruth, StateScore } from './types';
import { CALIBRATION_DOCS, CANONICAL_PLAN_IDENTITY_FIELDS } from './types';
import { summarizeGroundTruth } from './ground-truth';

function padRight(s: string, w: number): string {
  return s.length >= w ? s : s + ' '.repeat(w - s.length);
}

function padLeft(s: string, w: number): string {
  return s.length >= w ? s : ' '.repeat(w - s.length) + s;
}

export function generateMd(args: {
  scores: StateScore[];
  states: CalibrationState[];
  groundTruth: GroundTruth;
}): string {
  const { scores, states, groundTruth } = args;

  const lines: string[] = [];
  lines.push('# Calibration Progress Tracker');
  lines.push('');
  lines.push('> **IMPORTANT — do not compact.** Append-only progress log. Generated by `scripts/calibration/progress-tracker/run.ts`.');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Section 1: Methodology ────────────────────────────────────────────────
  lines.push('## Methodology');
  lines.push('');
  lines.push('**Primary metric**: `fields_verifiable` per (state, doc) — count of canonical fields where the Haiku-extracted value\'s `source_excerpt` round-trips against the OCR text via Pattern P-8 verification. **Monotonic improvement is the ship gate** — every new state must have `fields_verifiable >= prior_state_count` on every doc.');
  lines.push('');
  lines.push('**Opus role**: reference signal, not gold standard. Disagreements flagged for review but don\'t penalize the metric. (Per Andrew direction 2026-05-28 — "neither can be gold; Opus provides better reference data".)');
  lines.push('');
  lines.push('**Ground truth (Option E)**: per-(doc, field), derived from cross-state consistency of Opus baseline + Haiku-comprehensive ceiling. Both non-null and agreeing → field IS in doc; both null → field NOT in doc; otherwise ambiguous.');
  lines.push('');
  lines.push('**Verified null vs spurious null**: when Haiku returns null on a field where ground truth says the field is IN the doc, that\'s a spurious null (regression). When ground truth confirms absence, null is verified.');
  lines.push('');

  // ── Section 2: Ground truth coverage ──────────────────────────────────────
  lines.push('## Ground truth coverage');
  lines.push('');
  const gtSummary = summarizeGroundTruth(groundTruth);
  lines.push('| Doc | yes (present) | no (absent) | ambiguous | unknown | single_source |');
  lines.push('|---|---|---|---|---|---|');
  for (const [doc, counts] of Object.entries(gtSummary.per_doc)) {
    lines.push(`| ${doc} | ${counts.yes} | ${counts.no} | ${counts.ambiguous} | ${counts.unknown} | ${counts.single_source} |`);
  }
  lines.push(`| **Total** | **${gtSummary.total.yes}** | **${gtSummary.total.no}** | **${gtSummary.total.ambiguous}** | **${gtSummary.total.unknown}** | **${gtSummary.total.single_source}** |`);
  lines.push('');

  // ── Section 3: Per-state per-doc summary ──────────────────────────────────
  lines.push('## State-vs-state progress (per doc)');
  lines.push('');
  lines.push('Each row is a calibration state; each column group is a doc. Cells: `verifiable/17 | spurious-null | drift | fmt-fail | $`.');
  lines.push('');

  // Column headers
  const headerCells = ['State'];
  for (const doc of CALIBRATION_DOCS) {
    headerCells.push(doc.length > 18 ? doc.slice(0, 18) + '…' : doc);
  }
  headerCells.push('Σ cost');
  lines.push('| ' + headerCells.join(' | ') + ' |');
  lines.push('|' + headerCells.map(() => '---').join('|') + '|');

  for (const sc of scores) {
    const state = states.find((s) => s.id === sc.state_id);
    const label = state ? state.label.slice(0, 40) : sc.state_id;
    const row: string[] = [label];
    let totalCost = 0;
    for (const doc of CALIBRATION_DOCS) {
      const ds = sc.by_doc[doc];
      if (!ds) {
        row.push('—');
        continue;
      }
      totalCost += ds.cost_usd_total;
      const verifiable = `${ds.fields_verifiable}/${CANONICAL_PLAN_IDENTITY_FIELDS.length}`;
      const spurious = ds.spurious_null_count > 0 ? `**${ds.spurious_null_count}**` : '0';
      const drift = ds.drift_count > 0 ? `**${ds.drift_count}**` : '0';
      const fmt = ds.format_failure_count > 0 ? `**${ds.format_failure_count}**` : '0';
      const cost = ds.cost_usd_total > 0 ? `$${ds.cost_usd_total.toFixed(3)}` : '—';
      row.push(`${verifiable} · ${spurious}sn · ${drift}d · ${fmt}f · ${cost}`);
    }
    row.push(`$${totalCost.toFixed(3)}`);
    lines.push('| ' + row.join(' | ') + ' |');
  }
  lines.push('');
  lines.push('Legend: `sn` = spurious-null count, `d` = drift-key count, `f` = format-failure count. **Bold** = non-zero (problem signal).');
  lines.push('');

  // ── Section 4: Detailed per-state metrics ─────────────────────────────────
  lines.push('## Detailed per-state metrics');
  lines.push('');
  for (const sc of scores) {
    const state = states.find((s) => s.id === sc.state_id);
    lines.push(`### ${state?.label ?? sc.state_id}`);
    lines.push('');
    lines.push(`- **id**: \`${sc.state_id}\``);
    if (state) {
      lines.push(`- **model**: ${state.model}`);
      lines.push(`- **prompt**: ${state.prompt}`);
      lines.push(`- **temperature**: ${state.temperature === null ? '(N/A)' : state.temperature}`);
      lines.push(`- **tool_use**: ${state.tool_use ? 'YES' : 'no'}`);
    }
    lines.push('');
    lines.push('| Doc | verifiable | verified-null | unverifiable | spurious-null | drift | fmt-fail | Opus-agree | Opus-disagree | runs | $ | p50ms |');
    lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|');
    for (const doc of CALIBRATION_DOCS) {
      const ds = sc.by_doc[doc];
      if (!ds) {
        lines.push(`| ${doc} | — | — | — | — | — | — | — | — | — | — | — |`);
        continue;
      }
      lines.push(
        `| ${doc} | ${ds.fields_verifiable} | ${ds.verified_null_count} | ${ds.unverifiable_count} | ${ds.spurious_null_count} | ${ds.drift_count} | ${ds.format_failure_count} | ${ds.agreement_with_opus_count} | ${ds.disagreement_with_opus_count} | ${ds.total_runs} | $${ds.cost_usd_total.toFixed(4)} | ${ds.latency_ms_p50 ?? '—'} |`,
      );
    }
    lines.push('');
    // Value-vs-GT correctness table
    lines.push('**Value-vs-GT correctness** (stricter than excerpt verification — checks if Haiku\'s VALUE matches the adjudicated GT):');
    lines.push('');
    lines.push('| Doc | correct | wrong | verified_absent | false_positive | unscored_unknown | unscored_ambiguous |');
    lines.push('|---|---|---|---|---|---|---|');
    for (const doc of CALIBRATION_DOCS) {
      const ds = sc.by_doc[doc];
      if (!ds) {
        lines.push(`| ${doc} | — | — | — | — | — | — |`);
        continue;
      }
      lines.push(
        `| ${doc} | ${ds.value_correct_count} | ${ds.value_wrong_count > 0 ? '**' + ds.value_wrong_count + '**' : '0'} | ${ds.value_verified_absent_count} | ${ds.value_false_positive_count > 0 ? '**' + ds.value_false_positive_count + '**' : '0'} | ${ds.value_unscored_unknown_count} | ${ds.value_unscored_ambiguous_count} |`,
      );
    }
    lines.push('');
    // Drift keys detail
    const allDrift = new Set<string>();
    for (const doc of CALIBRATION_DOCS) {
      const ds = sc.by_doc[doc];
      ds?.drift_keys.forEach((k) => allDrift.add(k));
    }
    if (allDrift.size > 0) {
      lines.push(`**Drift keys observed**: ${Array.from(allDrift).sort().map((k) => `\`${k}\``).join(', ')}`);
      lines.push('');
    }
  }

  // ── Section 5: Monotonic improvement check ────────────────────────────────
  lines.push('## Monotonic improvement check (Ship Gate G2 evidence)');
  lines.push('');
  lines.push('Each Haiku state\'s `fields_verifiable` count compared against **two reference points**:');
  lines.push('');
  lines.push('- **vs DEFECT floor** (`haiku-live-prod-temp1-2026-05-28`) — the pre-Session-2 production baseline we\'re trying to improve. **Ship gate**: any new Haiku state must NOT regress vs DEFECT floor on any doc.');
  lines.push('- **vs Opus reference** (informational; Opus is reference data not gold) — track whether Haiku approaches or exceeds Opus.');
  lines.push('');
  const defectFloor = scores.find((s) => s.state_id.includes('haiku-live-prod-temp1'));
  const opusBaseline = scores.find((s) => s.state_id.startsWith('opus-baseline'));

  function deltaCell(cur: number | null, ref: number | null): string {
    if (cur === null || ref === null) return '—';
    const d = cur - ref;
    if (d > 0) return `+${d}`;
    if (d < 0) return `**${d}**`;
    return '0';
  }

  function verdictOf(curScore: typeof scores[number], ref: typeof scores[number]): string {
    let regressed = false;
    let improved = false;
    for (const doc of CALIBRATION_DOCS) {
      const c = curScore.by_doc[doc]?.fields_verifiable ?? null;
      const r = ref.by_doc[doc]?.fields_verifiable ?? null;
      if (c === null || r === null) continue;
      if (c - r < 0) regressed = true;
      if (c - r > 0) improved = true;
    }
    return regressed ? '**REGRESSED**' : improved ? 'IMPROVED' : 'NEUTRAL';
  }

  if (defectFloor) {
    lines.push(`### Δ vs DEFECT floor (\`${defectFloor.state_id}\`)`);
    lines.push('');
    lines.push('| State | OAP Δ | Ambetter Δ | Gold80 Δ | AnthemIN Δ | ECM-EOC Δ | Verdict |');
    lines.push('|---|---|---|---|---|---|---|');
    for (const sc of scores) {
      if (sc.state_id === defectFloor.state_id) continue;
      if (sc.state_id.startsWith('opus-')) continue;
      if (sc.state_id.startsWith('haiku-comprehensive-')) continue;
      const cells: string[] = [];
      const state = states.find((s) => s.id === sc.state_id);
      cells.push((state?.label ?? sc.state_id).slice(0, 50));
      for (const doc of CALIBRATION_DOCS) {
        const c = sc.by_doc[doc]?.fields_verifiable ?? null;
        const r = defectFloor.by_doc[doc]?.fields_verifiable ?? null;
        cells.push(deltaCell(c, r));
      }
      cells.push(verdictOf(sc, defectFloor));
      lines.push('| ' + cells.join(' | ') + ' |');
    }
    lines.push('');
  }

  if (opusBaseline) {
    lines.push(`### Δ vs Opus reference (\`${opusBaseline.state_id}\`) — informational`);
    lines.push('');
    lines.push('| State | OAP Δ | Ambetter Δ | Gold80 Δ | AnthemIN Δ | ECM-EOC Δ | Total Δ |');
    lines.push('|---|---|---|---|---|---|---|');
    for (const sc of scores) {
      if (sc.state_id === opusBaseline.state_id) continue;
      const cells: string[] = [];
      const state = states.find((s) => s.id === sc.state_id);
      cells.push((state?.label ?? sc.state_id).slice(0, 50));
      let totalDelta = 0;
      let hasData = false;
      for (const doc of CALIBRATION_DOCS) {
        const c = sc.by_doc[doc]?.fields_verifiable ?? null;
        const r = opusBaseline.by_doc[doc]?.fields_verifiable ?? null;
        cells.push(deltaCell(c, r));
        if (c !== null && r !== null) {
          totalDelta += c - r;
          hasData = true;
        }
      }
      cells.push(hasData ? (totalDelta > 0 ? `**+${totalDelta}**` : `${totalDelta}`) : '—');
      lines.push('| ' + cells.join(' | ') + ' |');
    }
    lines.push('');
  }

  // ── Adjudication queue: unknown-GT fields with tool-use extractions ───────
  const toolUseScore = scores.find((s) => s.state_id.includes('toolUse'));
  if (toolUseScore) {
    lines.push('## Adjudication queue — unknown-GT fields (tool-use extractions for manual review)');
    lines.push('');
    lines.push('Per Andrew direction (2026-05-28): Opus doesn\'t cover `groupNumber` / `isAcaCompliant` / `acaComplianceBasis`, so the harness can\'t auto-score them. Tool-use\'s extractions for these fields need manual review and persistence to `gold_overrides.json`.');
    lines.push('');
    for (const doc of CALIBRATION_DOCS) {
      const ds = toolUseScore.by_doc[doc];
      if (!ds) continue;
      const unknownFields = ds.per_field.filter((f) => f.value_match === 'unscored_unknown');
      if (unknownFields.length === 0) continue;
      lines.push(`### ${doc}`);
      lines.push('');
      for (const f of unknownFields) {
        const excerpt = f.haiku_excerpt ? `"${String(f.haiku_excerpt).slice(0, 120)}"` : '(no excerpt)';
        lines.push(`- \`${f.field}\`: value=\`${JSON.stringify(f.haiku_value)}\`, excerpt=${excerpt}, verified=${f.verified}`);
      }
      lines.push('');
    }
  }

  // ── Section 6: Opus disagreements (review queue) ──────────────────────────
  lines.push('## Opus disagreements (informational — for review, not penalty)');
  lines.push('');
  lines.push('Cases where Haiku state disagrees with Opus on a non-null value. Review to determine whether Opus is right OR Haiku is right OR both have plausible interpretations.');
  lines.push('');
  for (const sc of scores) {
    if (sc.state_id.startsWith('opus-')) continue; // don't compare Opus to itself
    const state = states.find((s) => s.id === sc.state_id);
    const disagreements: string[] = [];
    for (const doc of CALIBRATION_DOCS) {
      const ds = sc.by_doc[doc];
      if (!ds) continue;
      for (const f of ds.per_field) {
        if (f.disagrees_with_opus) {
          disagreements.push(`- **${doc}** / \`${f.field}\`: haiku=\`${JSON.stringify(f.haiku_value)}\` vs opus`);
        }
      }
    }
    if (disagreements.length === 0) continue;
    lines.push(`### ${state?.label ?? sc.state_id}`);
    lines.push('');
    for (const d of disagreements) lines.push(d);
    lines.push('');
  }

  return lines.join('\n');
}
