-- Session 35: Dispute lifecycle vocabulary + letter/evidence persistence
--
-- 1. Extend dispute_outcomes.status CHECK constraint with new lifecycle values:
--    - dispute_letter_drafted: letter generated (semantically replaces 'filed' for new rows;
--      legacy 'filed' rows remain valid and render as "Dispute Letter Drafted").
--    - court_documentation_drafted: evidence package generated for small claims.
--
-- Additive only — no existing rows are modified. Old values (filed, in_progress,
-- won, lost, settled, withdrawn, won_on_escalation, settled_on_escalation) remain
-- valid so legacy rows continue to work.
--
-- 2. Persist letter_content and evidence_package so users can view what was
--    drafted on their behalf from the claim detail Linked Disputes section.
-- ============================================================================

-- ── 1. Extend status CHECK constraint additively ──────────────────────────
DO $$
BEGIN
  ALTER TABLE dispute_outcomes DROP CONSTRAINT IF EXISTS dispute_outcomes_status_check;
EXCEPTION WHEN undefined_object THEN
  NULL;
END $$;

ALTER TABLE dispute_outcomes
  ADD CONSTRAINT dispute_outcomes_status_check
  CHECK (status IN (
    -- Legacy (preserved — no data migration)
    'filed',
    'in_progress',
    'won',
    'lost',
    'settled',
    'withdrawn',
    'won_on_escalation',
    'settled_on_escalation',
    -- New lifecycle vocabulary (Session 35)
    'dispute_letter_drafted',
    'court_documentation_drafted'
  ));

-- ── 2. Persist letter content + evidence package ──────────────────────────
-- Letter text generated by /api/disputes/generate so users can revisit it.
ALTER TABLE dispute_outcomes
  ADD COLUMN IF NOT EXISTS letter_content TEXT;

-- Evidence package generated by /api/legal/evidence-package (9-section
-- court document). Stored as JSONB so sections can be rendered independently.
ALTER TABLE dispute_outcomes
  ADD COLUMN IF NOT EXISTS evidence_package JSONB;

-- ── 3. Index for fast "show me all disputes with letters" queries ─────────
CREATE INDEX IF NOT EXISTS idx_dispute_outcomes_letter_drafted
  ON dispute_outcomes(user_id)
  WHERE letter_content IS NOT NULL;
